- packages/service/README.md
- packages/service/package-lock.json
- packages/service/src/commands/clean.ts
- packages/service/src/commands/dev.ts
- packages/service/src/commands/e2e.ts
- packages/service/src/commands/prettier.ts
This PR adds a new option to the dev task to open the dev env in the default browser
I cleaned up some duplicated aliases
no ticket
> feat(service): add option to open page in dev mode

- packages/service/README.md
- packages/service/src/commands/add.ts
- packages/service/src/commands/build.ts
- packages/service/src/commands/clean.ts
- packages/service/src/commands/create.ts
- packages/service/src/commands/dev.ts
- packages/service/src/commands/e2e.ts
- packages/service/src/commands/extract-messages.ts
- packages/service/src/commands/generate.ts
- packages/service/src/commands/lint.ts
- packages/service/src/commands/parallel.ts
- packages/service/src/commands/prettier.ts
- packages/service/src/commands/release.ts
- packages/service/src/commands/statistics.ts
- packages/service/src/commands/storybook.ts
- packages/service/src/commands/test.ts
- packages/service/src/commands/update.ts
- packages/service/src/index.ts
- packages/service/src/lib/command.ts
- packages/service/src/utils/process.ts
- packages/service/src/utils/ui.ts
closes #4
This PR removes the option `--silent` and adds a new global flag `--debug`. by default we don't allow users to silence the output, we only enable the user to get additional information via the `--debug` flag
nope
#4
> feat(service): add --debug flag

- packages/addon-contentful/src/ContentfulMiddleware.ts
I don't know 100% what causes the issue in our venture but I improved the error handling anyway.
nope
...
> feat(contentful): improve error handling

- packages/service/package-lock.json
- packages/service/package.json
- packages/service/src/commands/parallel.ts
closes #9
This PR updates the parallel task to use the npm package `concurrently` because it's battle tested
nope
#9
> feat(service): use concurrently for parallel command

- packages/addon-contentful/src/ContentfulMiddleware.ts
This will enhance the Middleware to accept arbitrarily nested data structures and consistently flatten them.
I decided to go with a recursive algorithm because, in theory, they could be nested `n` levels deep.
none
> feat: now transforms properties recursively

- packages/service/src/commands/parallel.ts
the ci passes currently because concurrently doesn't exit with an error. This PR will hopefully fix it as I now use the api as documented in their repository.
see https://github.com/kimmobrunfeldt/concurrently#programmatic-usage
no issue
> fix(service): handle error if concurrently fails

- packages/service/src/commands/test.ts
- packages/service/src/index.ts
- packages/service/src/models/Config.ts
- packages/service/src/utils/misc.ts
- packages/service/src/webpack/config/base.ts
related to https://github.com/devCrossNet/vue-starter/issues/390
This PR adds the possibility to configure webpack aliases
I don't have a common abstraction because I want to test it first, we can make it prettier later
https://github.com/devCrossNet/vue-starter/issues/390
> feat(service): config for webpack aliases

- packages/addon-contentful/package-lock.json
- packages/addon-contentful/package.json
- packages/addon-contentful/src/ContentfulMiddleware.ts
This will find any contentful rich text document and parse it using `@contentful/rich-text-html-renderer`.
as the documentation says:
- The document must have only one root node with `nodeType: 'document'`. 
[more here](https://www.contentful.com/developers/docs/concepts/rich-text/)
not really
or a link to a ticket system...
> feat(contentful): adds rich text renderer

- packages/addon-contentful/package-lock.json
- packages/addon-vuex-persist/package-lock.json
- packages/service/package-lock.json
- packages/service/src/scripts/Utils.spec.ts
- packages/service/src/scripts/Utils.ts
closes #7
see #7 
I followed the YAGNI principle and implemented a solution to solve only this one problem
#7
> fix(service): add new use-case to extract-i18n script

- .circleci/config.yml
- package-lock.json
- package.json
- packages/service/__tests__/e2e.spec.ts
- packages/service/package.json
- packages/service/src/commands/create.ts
- packages/service/src/commands/dev.ts
- packages/service/src/utils/process.ts
- packages/service/test/e2e.ts
- packages/service/tsconfig.json
closes #17
This PR adds basic e2e testing for the vuesion service for:
- create
- build
- build storybook
- test
- clean
I did some changes along side the tests
the e2e test is not included in the CI, I don't get npm link to work in circle ci so we at least have it for manual execution.
#17
> tests(service): add basic e2e testing

- packages/addon-contentful/package.json
- packages/addon-theme-switcher/.npmignore
- packages/addon-theme-switcher/README.md
- packages/addon-theme-switcher/package-lock.json
- packages/addon-theme-switcher/package.json
- packages/addon-theme-switcher/register.js
- packages/addon-theme-switcher/src/ThemeSwitcher.tsx
- packages/addon-theme-switcher/src/register.tsx
- packages/addon-theme-switcher/tsconfig.json
- packages/service/package.json
- packages/service/src/webpack/config/base.ts
- tsconfig.json
related to https://github.com/vuesion/vuesion/issues/391
This PR adds a new package that contains a Storybook addon to enable theme switching.
I added keywords to all existing packages.
https://github.com/vuesion/vuesion/issues/391
> feat: add addon-theme-switcher

- packages/addon-contentful/package-lock.json
- packages/addon-theme-switcher/package-lock.json
- packages/addon-vuex-persist/package-lock.json
- packages/create/package-lock.json
- packages/models/package-lock.json
- packages/service/package-lock.json
- packages/service/package.json
- packages/service/src/generators/ast.ts
- packages/service/src/generators/connected/index.ts
- packages/service/src/generators/crud-module/index.ts
- packages/service/src/generators/helpers.ts
- packages/service/src/generators/index.ts
- packages/service/src/generators/module/index.ts
- packages/utils/package-lock.json
- packages/webpack/package-lock.json
related to https://github.com/vuesion/vuesion/issues/442
This PR adds a new generator `CRUD module`,  this generator is supposed to generate a module with initial scaffolding for CRUD operations.
- a lot of duplication
- needs refactoring  in the future
https://github.com/vuesion/vuesion/issues/442
> feat(generators): add support for CRUD module

- packages/addon-contentful/package-lock.json
- packages/addon-theme-switcher/package-lock.json
- packages/addon-vuex-persist/package-lock.json
- packages/create/package-lock.json
- packages/models/package-lock.json
- packages/service/package-lock.json
- packages/service/src/generators/helpers.ts
- packages/utils/package-lock.json
- packages/webpack/package-lock.json
this PR changes the custom implementation for handlebars helpers to use the very well tested string operations of lodash
nope
no ticket
> refactor(generators): use lodash as handlebars helpers

- packages/models/src/JSONModel.ts
- packages/models/src/VuesionConfig.ts
- packages/service/package-lock.json
- packages/webpack/src/config/base-server.ts
- packages/webpack/src/config/client.ts
- packages/webpack/src/config/spa.ts
This PR adds the possibility to change the build output directory
nope
no ticket
> feat(service): add outputDirectory to VuesionConfig

- .eslintrc.js
- packages/addon-firebase/.npmignore
- packages/addon-firebase/README.md
- packages/addon-firebase/package-lock.json
- packages/addon-firebase/package.json
- packages/addon-firebase/src/FirebaseJSON.ts
- packages/addon-firebase/src/FirebaseRc.ts
- packages/addon-firebase/src/FunctionsPackage.ts
- packages/addon-firebase/src/ProductionConfig.ts
- packages/addon-firebase/src/TsConfig.ts
- packages/addon-firebase/src/index.ts
- packages/addon-firebase/template/.firebaserc
- packages/addon-firebase/template/firebase.json
- packages/addon-firebase/template/functions/.gitignore
- packages/addon-firebase/template/functions/package.json
- packages/addon-firebase/template/functions/src/index.ts
- packages/addon-firebase/template/functions/tsconfig.json
- packages/addon-firebase/template/src/server/index.ts
- packages/addon-firebase/tsconfig.json
- packages/models/package-lock.json
- packages/service/package-lock.json
- packages/service/src/commands/add.ts
- packages/webpack/package-lock.json
closes https://github.com/vuesion/vuesion/issues/482
This PR adds a new package for the firebase add-on
nope
https://github.com/vuesion/vuesion/issues/482
> feat: add addon-firebase

- packages/addon-vuetify/.npmignore
- packages/addon-vuetify/README.md
- packages/addon-vuetify/package-lock.json
- packages/addon-vuetify/package.json
- packages/addon-vuetify/src/App.ts
- packages/addon-vuetify/src/index.ts
- packages/addon-vuetify/template/src/app/app/App/App.vue
- packages/addon-vuetify/tsconfig.json
- packages/service/src/commands/add.ts
This PR add a new package for the vuetify add-on
nope
no ticket
> feat: add addon-vuetify

- packages/addon-firebase/template/firebase.json
- packages/addon-firebase/template/functions/package.json
- packages/models/package-lock.json
- packages/service/README.md
- packages/service/package-lock.json
- packages/service/src/commands/e2e.ts
- packages/service/src/commands/statistics.ts
- packages/service/src/commands/update.ts
- packages/service/src/index.ts
- packages/service/src/scripts/update.ts
- packages/webpack/package-lock.json
This PR add a `--next` option to the updarte command to update the local copy to the next version of vuesion
nope
no ticket
> feat(service): add --next option to update command

- packages/addon-tailwindcss/.npmignore
- packages/addon-tailwindcss/README.md
- packages/addon-tailwindcss/package-lock.json
- packages/addon-tailwindcss/package.json
- packages/addon-tailwindcss/src/index.ts
- packages/addon-tailwindcss/template/tailwind.config.js
- packages/addon-tailwindcss/tsconfig.json
- packages/models/src/VuesionWebpackConfig.ts
- packages/models/src/ast.ts
- packages/models/src/index.ts
- packages/service/package-lock.json
- packages/service/src/commands/add.ts
- packages/service/src/scripts/update.ts
- packages/webpack/package-lock.json
This PR adds a new addon for tailwindcss
nope
no ticket
> feat: add addon-tailwindcss

- packages/addon-tailwindcss/src/index.ts
there is a copy/paste issue in the webpack config which leads to an error
> fix(addon-tailwindcss): change scssRuleIndex selector

- package.json
- packages/create/src/commands/create.ts
- packages/models/package-lock.json
- packages/models/src/AppState.ts
- packages/service/package-lock.json
- packages/service/package.json
- packages/service/src/commands/post-install.ts
- packages/service/src/generators/component/index.ts
- packages/service/src/generators/index.ts
- packages/service/src/generators/page/index.ts
- packages/service/src/generators/vuex-module/index.ts
- packages/service/src/index.ts
- packages/service/src/scripts/extract-i18n-messages.ts
- packages/service/test/e2e.ts
- packages/vuex-persist/package-lock.json
- packages/vuex-persist/package.json
- packages/webpack/src/config/base-server.ts
- packages/webpack/src/config/base.ts
- packages/webpack/src/config/client.ts
This PR changes the packages in a way to support the new nuxt set up in the vuesion/nuxt branch
maybe?
related to https://github.com/vuesion/vuesion/issues/508
> feat: add nuxt support

- packages/service/src/scripts/Utils.spec.ts
- packages/service/src/scripts/Utils.ts
- packages/service/src/scripts/extract-i18n-messages.ts
> feat(service): support .t() in extract-i18n-messages

- packages/models/package-lock.json
- packages/service/package-lock.json
- packages/service/src/generators/index.ts
- packages/service/src/generators/interface/index.ts
> feat(service): add interface generator

- packages/models/package-lock.json
- packages/service/package-lock.json
- packages/service/src/commands/extract-messages.ts
- packages/service/src/scripts/extract-i18n-messages.ts
description...
please take a moment to tell us about your choices...
or a link to a ticket system...
> feat(service): add flag for setting default translations for i18n script

- packages/service/src/scripts/Utils.spec.ts
- packages/service/src/scripts/Utils.ts
description...
please take a moment to tell us about your choices...
or a link to a ticket system...
> feat(service): more use-cases for i18n script
